server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: hoteles-service
          uri: lb://HOTELES-SERVICE
          predicates:
            - Path=/hoteles/**
        - id: vuelos-service
          uri: lb://VUELOS-SERVICE
          predicates:
            - Path=/vuelos/**
        - id: reservas-service
          uri: lb://RESERVAS-SERVICE
          predicates:
            - Path=/reservas/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
